import { useState } from "react";
import { Link, useLocation } from "wouter";
import { ArrowRight, BookOpen, Github, Loader2, Sparkles } from "lucide-react";
import { OracleMark } from "@/components/OracleMark";
import { Button } from "@/components/ui/button";
import { saveActiveReading } from "@/lib/activeReading";
import { trpc } from "@/lib/trpc";

export default function Home() {
  const [, setLocation] = useLocation();
  const [repositoryUrl, setRepositoryUrl] = useState("");
  const [notice, setNotice] = useState<string | null>(null);
  const createReading = trpc.repository.analyze.useMutation({
    onSuccess: reading => { saveActiveReading(reading); setLocation("/reading"); },
    onError: error => setNotice(error.message),
  });
  const submit = (event: React.FormEvent) => { event.preventDefault(); setNotice(null); createReading.mutate({ repositoryUrl }); };
  return <div className="oracle-shell min-h-screen overflow-x-hidden"><header className="page-header"><Link href="/"><OracleMark /></Link><nav className="flex items-center gap-5"><a href="#how-it-works" className="nav-link">Method</a><Link href="/library" className="nav-link">Library</Link></nav></header>
    <main><section className="relative mx-auto grid max-w-7xl gap-14 px-5 pb-20 pt-16 md:px-8 lg:grid-cols-[1.08fr_0.92fr] lg:items-center lg:pt-24"><div className="absolute left-[-16rem] top-[-12rem] h-[32rem] w-[32rem] rounded-full bg-violet-500/15 blur-[110px]" /><div className="relative"><p className="eyebrow flex items-center gap-2"><Sparkles className="h-3 w-3" /> Evidence, interpretation, direction</p><h1 className="mt-6 max-w-3xl font-serif text-5xl leading-[0.96] text-amber-50 sm:text-6xl lg:text-7xl">Read the architecture beneath your code.</h1><p className="mt-7 max-w-xl text-base leading-8 text-slate-300">Paste a public GitHub repository. EsotericCode measures its visible structure, then pairs the signal with Tarot, I Ching, a KP-inspired chart, and clear technical next steps.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#consult" className="button-gold inline-flex h-11 items-center rounded-md px-5 text-sm font-semibold">Consult a repository <ArrowRight className="ml-2 h-4 w-4" /></a><Link href="/library" className="button-quiet inline-flex h-11 items-center rounded-md px-5 text-sm">Explore correspondences <BookOpen className="ml-2 h-4 w-4" /></Link></div><p className="mt-5 text-xs text-slate-500">No account, authorization, or email verification required.</p><div className="mt-12 grid max-w-xl grid-cols-3 gap-6 border-t border-white/10 pt-6"><div><p className="font-serif text-3xl text-amber-100">1</p><p className="mt-1 text-xs leading-5 text-slate-400">Public repository URL</p></div><div><p className="font-serif text-3xl text-amber-100">3</p><p className="mt-1 text-xs leading-5 text-slate-400">Complementary reading lenses</p></div><div><p className="font-serif text-3xl text-amber-100">0</p><p className="mt-1 text-xs leading-5 text-slate-400">Sign-in steps required</p></div></div></div>
      <section id="consult" className="relative oracle-panel rounded-3xl p-6 shadow-2xl shadow-black/30 md:p-8"><div className="flex items-start justify-between gap-6"><div><p className="eyebrow">Begin a reading</p><h2 className="mt-3 font-serif text-3xl text-amber-50">Consult a public repository</h2></div><span className="flex h-11 w-11 items-center justify-center rounded-full border border-amber-200/20 bg-amber-200/5"><Github className="h-5 w-5 text-amber-200" /></span></div><form className="mt-7" onSubmit={submit}><label className="label" htmlFor="repository-url">Public GitHub repository URL</label><input id="repository-url" value={repositoryUrl} onChange={event => setRepositoryUrl(event.target.value)} placeholder="github.com/owner/repository" className="oracle-input mt-2 min-w-0 text-base tracking-[-0.01em]" autoComplete="url" inputMode="url" spellCheck={false} dir="ltr" required />{repositoryUrl && <p className="mt-2 break-all text-[11px] leading-5 text-violet-200/80">Entered: {repositoryUrl}</p>}<p className="mt-3 text-xs leading-5 text-slate-400">We inspect GitHub’s public repository metadata and visible file tree. Your reading is held only in this browser session.</p><Button disabled={createReading.isPending} className="button-gold mt-6 w-full" type="submit">{createReading.isPending ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" /> Mapping repository</> : "Create repository reading"}</Button></form>{notice && <p role="status" className="mt-5 rounded-xl border border-amber-200/15 bg-amber-200/5 px-4 py-3 text-xs leading-5 text-amber-100">{notice}</p>}</section></section>
      <section id="how-it-works" className="border-y border-white/10 bg-black/10"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8"><div className="max-w-2xl"><p className="eyebrow">A legible method</p><h2 className="mt-4 font-serif text-4xl text-amber-50">Symbols follow the signals, not the other way around.</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3"><article className="method-card"><span>01</span><h3>Measure the tree</h3><p>We map visible files, module shape, entry points, source-to-test signals, contributors, recent commits, and structural complexity.</p></article><article className="method-card"><span>02</span><h3>Surface the pattern</h3><p>Architecture evidence stays visible alongside the reading, so every interpretation remains connected to a measurable repository condition.</p></article><article className="method-card"><span>03</span><h3>Choose a next move</h3><p>Three plain-language action cards translate the portrait into a small, practical sequence for your next technical decision.</p></article></div></div></section>
      <section className="mx-auto max-w-7xl px-5 py-20 md:px-8"><div className="rounded-3xl border border-white/10 bg-gradient-to-r from-violet-500/[0.11] via-slate-950 to-amber-300/[0.08] p-8 md:p-10"><p className="eyebrow">Public by design</p><h2 className="mt-3 font-serif text-3xl text-amber-50">One repository link. One immediate reading.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">EsotericCode reads only the public repository you provide. It does not ask for your GitHub account, private repository permissions, or a login to begin.</p></div></section>
    </main><footer className="border-t border-white/10 px-5 py-8 text-center text-xs text-slate-500">EsotericCode · An interpretive companion for deliberate software work</footer></div>;
}
