import { OracleMark } from "@/components/OracleMark";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import type { KpPlanetaryCorrespondence } from "@shared/esoteric";
import { BookOpen, ChevronRight, Loader2, Orbit, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";

type Tab = "tarot" | "iching" | "kp";
type LibraryTarotCard = { id: string; cardName: string; cardNumber: string; suit: string; mysticalInterpretation: string; technicalActionable: string; reversedInterpretation?: string; reversedAction?: string };
type LibraryHexagram = { number: number; name: string; chineseName: string; symbol?: string; classicalText: string; developerInterpretation: string };

function suitGlyph(suit: string) {
  return suit === "major" ? "✦" : suit === "wands" ? "♢" : suit === "cups" ? "◒" : suit === "swords" ? "†" : "⊕";
}

export default function Library() {
  const initialTab = new URLSearchParams(window.location.search).get("tab");
  const [tab, setTab] = useState<Tab>(initialTab === "kp" ? "kp" : initialTab === "iching" ? "iching" : "tarot");
  const { data, isLoading } = trpc.divination.library.useQuery();
  const [selectedTarotId, setSelectedTarotId] = useState<string | null>(null);
  const [selectedHexagramNumber, setSelectedHexagramNumber] = useState<number | null>(null);
  const tarot = data?.tarot ?? [];
  const hexagrams = data?.hexagrams ?? [];
  const kpPlanets = data?.kpPlanets ?? [];
  const selectedTarot = useMemo(() => tarot.find(card => card.id === (selectedTarotId ?? tarot[0]?.id)) ?? tarot[0], [tarot, selectedTarotId]);
  const selectedHexagram = useMemo(() => hexagrams.find(hexagram => hexagram.number === (selectedHexagramNumber ?? hexagrams[0]?.number)) ?? hexagrams[0], [hexagrams, selectedHexagramNumber]);

  return <div className="oracle-shell min-h-screen"><header className="page-header"><Link href="/"><OracleMark /></Link><Link href="/"><Button variant="ghost" className="text-slate-300 hover:bg-white/5 hover:text-white">Begin a reading <ChevronRight className="ml-1 h-4 w-4" /></Button></Link></header><main className="mx-auto max-w-7xl px-5 pb-20 pt-9 md:px-8"><div className="fade-up"><p className="eyebrow">The complete symbolic system</p><h1 className="mt-3 max-w-4xl font-display text-5xl text-amber-50 md:text-7xl">The library behind<br /><em className="text-amber-200">every reading.</em></h1><p className="mt-5 max-w-2xl text-sm leading-7 text-slate-400">The full Tarot and I Ching systems now meet a KP-inspired repository chart. Each planet’s engineering theme acts as a bridge across all three symbolic languages.</p></div><div className="library-tabs mt-10"><button className={tab === "tarot" ? "is-active" : ""} onClick={() => setTab("tarot")}><Sparkles className="mr-2 h-4 w-4" />Tarot deck <span>78 × 2</span></button><button className={tab === "iching" ? "is-active" : ""} onClick={() => setTab("iching")}><BookOpen className="mr-2 h-4 w-4" />I Ching <span>64</span></button><button className={tab === "kp" ? "is-active" : ""} onClick={() => setTab("kp")}><Orbit className="mr-2 h-4 w-4" />KP atlas <span>9</span></button></div>{isLoading ? <div className="flex h-96 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-amber-200" /></div> : tab === "tarot" && selectedTarot ? <TarotCatalog tarot={tarot} selected={selectedTarot} onSelect={setSelectedTarotId} /> : tab === "iching" && selectedHexagram ? <IChingCatalog hexagrams={hexagrams} selected={selectedHexagram} onSelect={setSelectedHexagramNumber} /> : <KpAtlas planets={kpPlanets} />}</main></div>;
}

function TarotCatalog({ tarot, selected, onSelect }: { tarot: LibraryTarotCard[]; selected: LibraryTarotCard; onSelect: (id: string) => void }) {
  return <section className="mt-8 grid gap-7 xl:grid-cols-[1fr_330px]"><div className="library-deck" aria-label="Complete Tarot deck">{tarot.map((card, index) => <button key={card.id} className={`library-tarot ${selected.id === card.id ? "is-selected" : ""}`} onClick={() => onSelect(card.id)}><span className="font-mono text-[10px] text-amber-200/90">{card.cardNumber}</span><span className="library-card-glyph">{suitGlyph(card.suit)}</span><span className="font-display text-center text-sm leading-tight text-amber-50">{card.cardName}</span><span className="font-mono text-[8px] uppercase tracking-[.15em] text-violet-200/60">UPRIGHT · REVERSED</span><i className="sr-only">Card {index + 1} of 78, with upright and reversed meanings</i></button>)}</div><aside className="library-detail xl:sticky xl:top-6 xl:self-start"><p className="eyebrow">Selected card · two expressions</p><div className="library-detail__symbol">{suitGlyph(selected.suit)}</div><p className="font-mono text-xs text-amber-200">{selected.cardNumber}</p><h2 className="mt-2 font-display text-3xl text-amber-50">{selected.cardName}</h2><div className="orientation-library-section"><p className="orientation-label">↥ Upright expression</p><p className="mt-2 text-sm leading-7 text-slate-300">{selected.mysticalInterpretation}</p><p className="mt-3 border-l border-amber-300/60 pl-3 text-sm leading-6 text-amber-100/90">{selected.technicalActionable}</p></div><div className="orientation-library-section is-reversed"><p className="orientation-label">↧ Reversed expression</p><p className="mt-2 text-sm leading-7 text-slate-300">{selected.reversedInterpretation}</p><p className="mt-3 border-l border-rose-300/60 pl-3 text-sm leading-6 text-rose-100/90">{selected.reversedAction}</p></div></aside></section>;
}

function IChingCatalog({ hexagrams, selected, onSelect }: { hexagrams: LibraryHexagram[]; selected: LibraryHexagram; onSelect: (number: number) => void }) {
  return <section className="mt-8"><div className="library-cast-guide"><div><p className="eyebrow">Complete six-line method</p><h2 className="mt-2 font-display text-3xl text-amber-50">Every hexagram can remain still or become another.</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-300">Each repository cast has six bottom-to-top lines. Values 6 and 9 are changing lines; they transform the primary hexagram into its relating hexagram. Values 7 and 8 remain stable.</p></div><div className="library-cast-values"><span><b>6</b> old yin · changes to yang</span><span><b>7</b> young yang · stable</span><span><b>8</b> young yin · stable</span><span><b>9</b> old yang · changes to yin</span></div></div><div className="mt-7 grid gap-7 xl:grid-cols-[1fr_330px]"><div className="hexagram-index" aria-label="All 64 I Ching hexagrams">{hexagrams.map(hexagram => <button key={hexagram.number} className={`hexagram-index__item ${selected.number === hexagram.number ? "is-selected" : ""}`} onClick={() => onSelect(hexagram.number)}><span className="hexagram-index__symbol">{hexagram.symbol}</span><span className="font-mono text-[10px] text-amber-200">{String(hexagram.number).padStart(2, "0")}</span><span className="min-w-0"><b className="block truncate font-display text-base font-medium text-amber-50">{hexagram.name}</b><span className="font-mono text-[10px] text-violet-200/65">{hexagram.chineseName}</span></span></button>)}</div><aside className="library-detail xl:sticky xl:top-6 xl:self-start"><p className="eyebrow">Hexagram {selected.number}</p><div className="library-detail__symbol font-serif">{selected.symbol}</div><p className="font-mono text-xs text-amber-200">{selected.chineseName}</p><h2 className="mt-2 font-display text-3xl text-amber-50">{selected.name}</h2><blockquote className="mt-5 border-l border-amber-300/60 pl-4 font-display text-lg italic leading-relaxed text-amber-50">“{selected.classicalText}”</blockquote><p className="mt-6 text-sm leading-7 text-slate-300">{selected.developerInterpretation}</p></aside></div></section>;
}

function KpAtlas({ planets }: { planets: KpPlanetaryCorrespondence[] }) {
  return <section className="kp-atlas mt-8" aria-label="KP correspondence atlas"><div className="kp-atlas__note"><p className="eyebrow">KP-inspired symbolic correspondences</p><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-300">A traditional KP chart depends on precise human birth time and location. EsotericCode instead uses this as an explicit repository-symbolic framework: each significator corresponds to engineering focus, Tarot archetypes, and I Ching hexagrams, while repository creation time and code signals determine the active chart.</p></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{planets.map(planet => <article className="kp-atlas-card" key={planet.planet}><div className="flex items-start justify-between"><span className="kp-atlas-card__symbol">{planet.symbol}</span><span className="eyebrow">{planet.planet}</span></div><h2 className="mt-4 font-display text-2xl text-amber-50">{planet.planet}</h2><p className="mt-3 text-sm leading-6 text-slate-300">{planet.engineeringFocus}</p><div className="mt-5"><p className="font-mono text-[10px] text-violet-200">TAROT</p><div className="mt-2 flex flex-wrap gap-2">{planet.tarotResonances.map(card => <span className="kp-chip" key={card}>{card}</span>)}</div></div><div className="mt-4"><p className="font-mono text-[10px] text-violet-200">I CHING</p><div className="mt-2 flex flex-wrap gap-2">{planet.hexagramResonances.map(hexagram => <span className="kp-chip" key={hexagram.number}>{hexagram.number}. {hexagram.name}</span>)}</div></div></article>)}</div></section>;
}
