import { MetricBar } from "@/components/MetricBar";
import { OracleMark } from "@/components/OracleMark";
import { TarotCardView } from "@/components/TarotCardView";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import type { KpAstrologyChart } from "@shared/esoteric";
import { Compass, Loader2, Sparkles } from "lucide-react";
import { Link, useRoute } from "wouter";

export default function SharedReading() {
  const [, params] = useRoute("/share/:shareSlug");
  const query = trpc.readings.shared.useQuery({ shareSlug: params?.shareSlug || "" }, { enabled: Boolean(params?.shareSlug) });
  if (query.isLoading) return <div className="oracle-shell flex min-h-screen items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-amber-200" /></div>;
  if (!query.data) return <div className="oracle-shell flex min-h-screen items-center justify-center p-6 text-center"><div><OracleMark /><h1 className="mt-9 font-display text-4xl text-amber-50">This reading has returned to the archive.</h1><Link href="/"><Button className="mystic-button mt-6">Visit EsotericCode</Button></Link></div></div>;
  const { metrics, tarot, iching, narrative } = query.data;
  const kp = metrics.kpChart;
  return <div className="oracle-shell min-h-screen"><header className="page-header"><Link href="/"><OracleMark /></Link><Link href="/"><Button variant="ghost" className="text-slate-300 hover:bg-white/5 hover:text-white"><Compass className="mr-2 h-4 w-4" />Consult your code</Button></Link></header><main className="mx-auto max-w-5xl px-5 pb-20 pt-12 md:px-8"><p className="eyebrow">A shared repository reading</p><h1 className="mt-4 font-display text-5xl text-amber-50 md:text-7xl">{metrics.owner}<span className="text-violet-300">/</span>{metrics.name}</h1><div className="mt-12 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div className="oracle-narrative"><div className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-amber-200" /><span className="eyebrow">The oracle speaks</span></div><p className="mt-6 font-display text-2xl leading-[1.55] text-amber-50">{narrative}</p></div><div className="panel p-6"><MetricBar label="Complexity" value={metrics.complexityScore * 15} detail={metrics.complexityLevel.toUpperCase()} tone={metrics.complexityLevel === "high" ? "rose" : "violet"} /><div className="mt-6"><MetricBar label="Test signal" value={metrics.testRatio * 100} detail={`${Math.round(metrics.testRatio * 100)}%`} tone="amber" /></div><div className="mt-6"><MetricBar label="Commit current" value={Math.min(metrics.recentCommitCount * 5, 100)} detail={`${metrics.recentCommitCount} / 30D`} /></div></div></div><section className="mt-14"><div className="section-heading"><div><p className="eyebrow">Tarot spread</p><h2 className="font-display text-3xl text-amber-50">What the repository reveals</h2></div></div><div className="mt-7 grid gap-5 md:grid-cols-3">{tarot.map((card, index) => <TarotCardView key={card.position} card={card} index={index} />)}</div></section><section className="mt-14 panel p-7"><p className="eyebrow">I Ching · {iching.chineseName}</p><h2 className="mt-3 font-display text-3xl text-amber-50">{iching.number}. {iching.name}</h2><blockquote className="mt-5 border-l border-amber-300/70 pl-5 font-display text-xl italic leading-relaxed text-amber-50">“{iching.classicalText}”</blockquote><p className="mt-6 max-w-3xl text-sm leading-7 text-slate-300">{iching.developerInterpretation}</p></section>{kp && <SharedKpBridge chart={kp} />}</main></div>;
}

function SharedKpBridge({ chart }: { chart: KpAstrologyChart }) { return <section className="kp-synthesis mt-14"><p className="eyebrow">KP correspondence layer</p><div className="mt-4 flex flex-wrap items-center gap-x-4 gap-y-2"><span className="font-display text-2xl text-amber-50">{chart.starLord.symbol} {chart.starLord.planet}</span><span className="font-mono text-xs text-violet-200">STAR LORD</span><span className="text-slate-600">/</span><span className="font-display text-2xl text-amber-50">{chart.subLord.symbol} {chart.subLord.planet}</span><span className="font-mono text-xs text-violet-200">SUB-LORD</span></div><p className="mt-5 font-display text-xl leading-relaxed text-amber-50">{chart.synthesis}</p><div className="mt-5 flex flex-wrap gap-2">{chart.tarotBridge.map(card => <span className="kp-chip" key={card}>{card}</span>)}{chart.ichingBridge.map(hexagram => <span className="kp-chip" key={hexagram.number}>{hexagram.number}. {hexagram.name}</span>)}</div><p className="mt-5 font-mono text-[10px] leading-5 text-slate-500">{chart.disclaimer}</p></section>; }
