import type { IChingCast, IChingLine } from "@shared/esoteric";

function LineGlyph({ line }: { line: IChingLine }) {
  return <span className={`iching-line-glyph ${line.polarity} ${line.changing ? "is-changing" : ""}`} aria-label={`${line.polarity}${line.changing ? ", changing" : ", stable"}`}><i /><i /></span>;
}

export function IChingCastView({ cast, compact = false }: { cast?: IChingCast; compact?: boolean }) {
  if (!cast) return null;
  const activeLines = cast.lines.filter(line => line.changing);
  return <section className={`iching-cast ${compact ? "is-compact" : ""}`}><div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><p className="eyebrow">Six-line cast · {cast.mode === "changing" ? "active transformation" : "static condition"}</p><h3 className="mt-2 font-display text-2xl text-amber-50">{cast.mode === "changing" ? `${activeLines.length} line${activeLines.length === 1 ? "" : "s"} in motion` : "All six lines are stable"}</h3></div><span className="font-mono text-[10px] tracking-[.14em] text-violet-200">BOTTOM → TOP · 6 / 7 / 8 / 9</span></div><div className="mt-6 grid gap-5 lg:grid-cols-[1fr_.9fr]"><div className="iching-lines">{cast.lines.slice().reverse().map(line => <div className={`iching-line ${line.changing ? "is-changing" : ""}`} key={line.position}><span className="font-mono text-[10px] text-slate-500">{line.position}</span><LineGlyph line={line} /><span className="min-w-0"><b className="block font-mono text-[10px] uppercase tracking-[.11em] text-violet-100">{line.positionName} · {line.value} · {line.changing ? "changing" : "stable"}</b><span className="mt-1 block text-xs leading-5 text-slate-400">{line.interpretation}</span></span></div>)}</div><div className="iching-transition"><p className="eyebrow">Direction of change</p>{cast.relatingHexagram ? <><div className="mt-5 flex items-center gap-4"><div className="iching-transition__symbol">{cast.relatingHexagram.symbol ?? "☷"}</div><div><p className="font-mono text-xs text-amber-200">RELATING HEXAGRAM</p><h4 className="mt-1 font-display text-2xl text-amber-50">{cast.relatingHexagram.number}. {cast.relatingHexagram.name}</h4><p className="mt-1 font-mono text-[11px] text-violet-200">{cast.relatingHexagram.chineseName}</p></div></div><p className="mt-5 text-sm leading-7 text-slate-300">{cast.relatingHexagram.developerInterpretation}</p></> : <div className="mt-5 rounded-xl border border-white/10 bg-black/10 p-4"><p className="font-display text-xl text-amber-50">No relating hexagram</p><p className="mt-2 text-sm leading-6 text-slate-400">This is a static cast. The primary hexagram remains the full counsel because no line is turning.</p></div>}<p className="mt-5 border-t border-white/10 pt-4 text-sm leading-6 text-violet-100/85">{cast.transformationSummary}</p></div></div></section>;
}
